import { Platform } from "react-native";

module.exports = {
  MainScreen: {
    marginTop: 50,
    marginBottom: 50,
    display: "flex",
    flexDirection: "column",
    backgroundColor: "black",
    width: "100%",
    height: "100%",
    alignItems: "center",
  },
  MainScreenText: {
    color: "white",
    fontSize: 50,
    textAlign: "right",
  },
  MainScreenDisplay: {
    width: "95%",
    height: '75%',
    backgroundColor: "black",
    padding: 10,
    marginBottom: 10,
    marginTop: 30,
    display: "flex",
    borderColor: "black",
    borderWidth: 5,
    borderRadius: 10,
    shadowColor: "#00f",
    shadowOffset: {
      width: 0,
      height: 40,
    },
    shadowOpacity: 0.6,
    shadowRadius: 15,
    elevation: Platform.OS === "android" ? 15 : 0,
  },
  MainScreenKeypad: {
    width: '95%',
    height: '65%',
    display: 'flex',
    marginBottom: 30
  },
  MainScreenKeypadRow: {
    display:'flex',
    flexDirection:'row',
    width:'100%', // Adjusted width
    justifyContent:'space-between',
    alignItems: 'center',
    padding: 5,
  },
  btn1_outer: {
    width: 90,
    height: 90,
    backgroundColor: '#505050',
    padding: 10,
    borderColor: "black",
    borderWidth: 5,
    borderRadius: 90,
    shadowColor: "black",
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.6,
    shadowRadius: 15,
    elevation: Platform.OS === "android" ? 15 : 0,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bg1_button: {
    backgroundColor: '#505050',
    color: 'white',
    fontSize: 40,
    borderRadius: 20,
  },
  btn_outer: {
    width: 90,
    height: 90,
    backgroundColor: "#D4D4D2",
    padding: 10,
    borderColor: "black",
    borderWidth: 5,
    borderRadius: 90,
    shadowColor: "black",
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.6,
    shadowRadius: 15,
    elevation: Platform.OS === "android" ? 15 : 0,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bg_button: {
    backgroundColor: "#D4D4D2",
    color: 'black',
    fontSize: 30,
    borderRadius: 20,
  },
  btn2_outer: {
    width: 90,
    height: 90,
    backgroundColor: "#FF9500",
    padding: 10,
    borderColor: "black",
    borderWidth: 5,
    borderRadius: 90,
    shadowColor: "#00f",
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.6,
    shadowRadius: 15,
    elevation: Platform.OS === "android" ? 15 : 0,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bg2_button: {
    backgroundColor: "#FF9500",
    color: 'white',
    fontSize: 40,
    borderRadius: 20,
  },
  btn3_outer: {
    width: 180,
    height: 90,
    backgroundColor: "#505050",
    padding: 10,
    borderColor: "black",
    borderWidth: 5,
    borderRadius: 90,
    shadowColor: "#00f",
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.6,
    shadowRadius: 15,
    elevation: Platform.OS === "android" ? 15 : 0,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bg3_button: {
    backgroundColor: "#505050",
    color: 'white',
    fontSize: 30,
    borderRadius: 20,
  }
};
